version: "3.8"

services:
  api01: &api
    build: ./api
    hostname: api01
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://rinha:rinha-password@db/rinha_db
      - REDIS_URL=redis://redis:6379/0
      - RUBY_GC_HEAP_INIT_SLOTS=200000
      - RUBY_GC_HEAP_FREE_SLOTS=100000
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "85MB"
    networks:
      - rinha-net

  api02:
    <<: *api

  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha-password
      - POSTGRES_DB=rinha_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/performance.conf:/etc/postgresql/performance.conf
    command: postgres -c 'config_file=/etc/postgresql/performance.conf'
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"
    networks:
      - rinha-net

  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "15MB"
    networks:
      - rinha-net
  
  redis:
    image: redis:7.2-alpine
    hostname: redis
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "15MB"

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true